### PR TITLE
Added feature to increase root's geometric error

### PR DESCRIPTION
**Pull request by majos95**
#18

### CODE REVIEW

**Comment by mfbonfigli** [comment]
I like the idea, however I think we could improve the code a bit by passing to the constructor instead of the multiplication factor an entire function that takes a node and returns a float64. The function is the strategy to use to compute the geometric error. This way just by swapping the function we can change the strategy the node has to use to compute the error, and its more futureproof with small added complexity.

Happy to receive feedback on this idea!

**Comment by majos95** [comment]
I like the idea, I'll wait until you check the issue regarding the geometric error. In case you agree that the root geometric error is too low, it would be as simple as checking if we are processing the root and multiplying by a higher value.

**Comment by mfbonfigli** [comment]
Checked that computation and indeed is wrong at the root, more details in the related issue. I think we should fix the computation of the error for the root as suggested there but also keep your scale factor to allow the user to do fine tuning if required.
Check it out when you have a sec and feel free to update the CR with that snippet if it works decently enough, I've done a quick test locally with a point cloud I have and indeed it seems to have appropriately improved the rendering distance at the first lod

**Comment by mfbonfigli** [comment]
Closing as the related fix has been introduced in a separate commit on release 1.2.1.

**Pull request closed without merging**
